### ISSUE TITLE
Unable to handle kernel write to read-only memory - Recore A7 Rebuild 1.0.1 RC6

### ISSUE THREAD

**Issue by obgr** [intelligent-agent/Rebuild#52] opened 2024-06-07 19:39 UTC
Rebuild 1.0.1 RC6 (Fluidd)
Recore A7

Got this an 70~ min after flash.
Standard klipper config.

stdout:
```
debian@recore:~$
Message from syslogd@recore at Jun  7 17:47:41 ...
 kernel:[ 4661.472390] Internal error: Oops: 000000009600004f [#1] SMP

Message from syslogd@recore at Jun  7 17:47:41 ...
 kernel:[ 4661.700216] Code: 37200121 12000c21 d2800082 9ac12041 (d50b7420)

debian@recore:~$

```

from syslog:
```bash
2024-06-07T17:47:40.935869+00:00 recore kernel: [ 4661.411308] Unable to handle kernel write to read-only memory at virtual address ffff0000002cd000
2024-06-07T17:47:40.935995+00:00 recore kernel: [ 4661.420378] Mem abort info:
2024-06-07T17:47:40.936004+00:00 recore kernel: [ 4661.423265]   ESR = 0x000000009600004f
2024-06-07T17:47:40.944884+00:00 recore kernel: [ 4661.427044]   EC = 0x25: DABT (current EL), IL = 32 bits
2024-06-07T17:47:40.944925+00:00 recore kernel: [ 4661.432376]   SET = 0, FnV = 0
2024-06-07T17:47:40.951094+00:00 recore kernel: [ 4661.435443]   EA = 0, S1PTW = 0
2024-06-07T17:47:40.951111+00:00 recore kernel: [ 4661.438592]   FSC = 0x0f: level 3 permission fault
2024-06-07T17:47:40.962616+00:00 recore kernel: [ 4661.443393] Data abort info:
2024-06-07T17:47:40.962631+00:00 recore kernel: [ 4661.446270]   ISV = 0, ISS = 0x0000004f
2024-06-07T17:47:40.962637+00:00 recore kernel: [ 4661.450112]   CM = 0, WnR = 1
2024-06-07T17:47:40.972324+00:00 recore kernel: [ 4661.453091] swapper pgtable: 4k pages, 48-bit VAs, pgdp=00000000413bc000
2024-06-07T17:47:40.972389+00:00 recore kernel: [ 4661.459808] [ffff0000002cd000] pgd=180000007fff7003, p4d=180000007fff7003, pud=180000007fff6003, pmd=180000007fff4003, pte=00600000402cd783
2024-06-07T17:47:41.223677+00:00 recore kernel: [ 4661.472390] Internal error: Oops: 000000009600004f [#1] SMP
2024-06-07T17:47:41.223818+00:00 recore kernel: [ 4661.477977] Modules linked in: nf_nat_h323 nf_conntrack_h323 nf_nat_pptp nf_conntrack_pptp nf_nat_tftp nf_conntrack_tftp nf_nat_sip nf_conntrack_sip nf_nat_irc nf_conntrack_irc nf_nat_ftp nf_conntrack_ftp nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 lz4hc lz4 zram binfmt_misc polyval_ce polyval_generic 8821cu axp20x_adc axp20x_ac_power axp20x_battery cfg80211 snd_soc_hdmi_codec rfkill cdc_acm sunxi_cedrus(C) v4l2_mem2mem videobuf2_dma_contig sun4i_gpadc_iio sun8i_a33_mbus videobuf2_memops videobuf2_v4l2 videobuf2_common videodev mc cpufreq_dt usb_f_acm u_serial g_serial libcomposite fuse dm_mod axp20x_usb_power pinctrl_axp209 industrialio realtek dw_hdmi_i2s_audio dw_hdmi_cec lima gpu_sched drm_shmem_helper dwmac_sun8i mdio_mux display_connector
2024-06-07T17:47:41.223831+00:00 recore kernel: [ 4661.544545] CPU: 2 PID: 8286 Comm: python Tainted: G         C         6.1.91-legacy-sunxi64 #26
2024-06-07T17:47:41.223838+00:00 recore kernel: [ 4661.553327] Hardware name: Recore-A7 (DT)
2024-06-07T17:47:41.223846+00:00 recore kernel: [ 4661.557335] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
2024-06-07T17:47:41.223855+00:00 recore kernel: [ 4661.564294] pc : clear_page+0x18/0x50
2024-06-07T17:47:41.223862+00:00 recore kernel: [ 4661.567978] lr : get_page_from_freelist+0xe90/0x106c
2024-06-07T17:47:41.223870+00:00 recore kernel: [ 4661.572952] sp : ffff80000efeb9d0
2024-06-07T17:47:41.223877+00:00 recore kernel: [ 4661.576260] x29: ffff80000efeb9d0 x28: ffff00003fdbf040 x27: fffffc000000b340
2024-06-07T17:47:41.223885+00:00 recore kernel: [ 4661.583395] x26: 0000000000000881 x25: 0000000000000000 x24: 0000000000000001
2024-06-07T17:47:41.223891+00:00 recore kernel: [ 4661.590528] x23: fffffc000000b340 x22: 0000000000000000 x21: ffff000000000000
2024-06-07T17:47:41.223898+00:00 recore kernel: [ 4661.597662] x20: 000000000000b380 x19: 000000000000b380 x18: 0000000000000000
2024-06-07T17:47:41.223906+00:00 recore kernel: [ 4661.604795] x17: 0000000000000000 x16: ffff800008f4cf88 x15: 0000000000000001
2024-06-07T17:47:41.223912+00:00 recore kernel: [ 4661.611928] x14: 0000000000000003 x13: 0000000000003c46 x12: ffff80000efebd28
2024-06-07T17:47:41.223920+00:00 recore kernel: [ 4661.619062] x11: ffff0000071a8400 x10: ffff0000071a8408 x9 : ffff0000071a840c
2024-06-07T17:47:41.223927+00:00 recore kernel: [ 4661.626196] x8 : 0000000000000000 x7 : 0000000000000000 x6 : 0000000000000000
2024-06-07T17:47:41.223936+00:00 recore kernel: [ 4661.633328] x5 : ffff800036af8000 x4 : 0000000000000030 x3 : ffff800036af8000
2024-06-07T17:47:41.223942+00:00 recore kernel: [ 4661.640460] x2 : 0000000000000004 x1 : 0000000000000040 x0 : ffff0000002cd000
2024-06-07T17:47:41.223948+00:00 recore kernel: [ 4661.647595] Call trace:
2024-06-07T17:47:41.223954+00:00 recore kernel: [ 4661.650041]  clear_page+0x18/0x50
2024-06-07T17:47:41.223960+00:00 recore kernel: [ 4661.653358]  __alloc_pages+0x168/0xccc
2024-06-07T17:47:41.223967+00:00 recore kernel: [ 4661.657112]  __folio_alloc+0x1c/0x5c
2024-06-07T17:47:41.224025+00:00 recore kernel: [ 4661.660689]  vma_alloc_folio+0xb4/0x330
2024-06-07T17:47:41.224034+00:00 recore kernel: [ 4661.664529]  alloc_zeroed_user_highpage_movable+0x3c/0x50
2024-06-07T17:47:41.224041+00:00 recore kernel: [ 4661.669940]  __handle_mm_fault+0x5ac/0xd70
2024-06-07T17:47:41.224047+00:00 recore kernel: [ 4661.674043]  handle_mm_fault+0xc0/0x240
2024-06-07T17:47:41.224052+00:00 recore kernel: [ 4661.677878]  do_page_fault+0x170/0x3e0
2024-06-07T17:47:41.224058+00:00 recore kernel: [ 4661.681635]  do_translation_fault+0xac/0xc0
2024-06-07T17:47:41.224065+00:00 recore kernel: [ 4661.685819]  do_mem_abort+0x44/0x94
2024-06-07T17:47:41.224071+00:00 recore kernel: [ 4661.689307]  el0_da+0x30/0x90
2024-06-07T17:47:41.224077+00:00 recore kernel: [ 4661.692276]  el0t_64_sync_handler+0xf8/0x140
2024-06-07T17:47:41.224083+00:00 recore kernel: [ 4661.696542]  el0t_64_sync+0x18c/0x190
2024-06-07T17:47:41.224089+00:00 recore kernel: [ 4661.700216] Code: 37200121 12000c21 d2800082 9ac12041 (d50b7420)
2024-06-07T17:47:41.224096+00:00 recore kernel: [ 4661.706305] ---[ end trace 0000000000000000 ]---

```

**Comment by eliasbakken** [comment] 2024-06-09 20:42
I think this is a memory corruption issue similar to what we have seen before on A6. 
I've ran my A7 for a bit locally and I'd not seen anything so far. I need to be able to reproduce the issue in order to help out.

**Comment by eliasbakken** [comment] 2024-06-11 08:30
We are moving ahead with the launch of v1.0.1 despite this issue, but we keep it open and keep an eye on it.

**Comment by obgr** [comment] 2024-06-11 08:48
I have **not** been able to reproduce this with memory tests with memtester.
I will continue to monitor if this happens again.

**Comment by obgr** [comment] 2024-06-12 21:36
Got another error, but i do not have the trace back, only stdout
```bash
Message from syslogd@recore at Jun 12 21:17:14 ...
 kernel:[   65.480569] Internal error: Oops: 0000000096000004 [#1] SMP

Message from syslogd@recore at Jun 12 21:17:14 ...
 kernel:[   65.715072] Code: aa1303e1 aa1403e0 97ffddab aa0003f3 (f9404014)
```

**Comment by eliasbakken** [comment] 2024-06-25 08:35
I got a similar error now on rev A8. 
![image](https://github.com/intelligent-agent/Rebuild/assets/3756249/e5d6fa20-1f8c-4d4b-844d-710e8c104aa2)

**Comment by eliasbakken** [comment] 2024-06-27 13:17
This seems to be OK now. A cleaned up patch has been merged, so we should just double check that everything is still OK. Closing for now and making RC2.

**Closed by eliasbakken** 2024-06-27 13:17 UTC
Labels: bug
